### ISSUE TITLE
Method definition warning 

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaNLSolvers/NLsolve.jl#168]
Is this expected?
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using NLsolve
WARNING: Method definition (::Type{NLSolversBase.OnceDifferentiable{TF, TDF, TX} where TX where TDF where TF})(Any, AbstractArray{T, N} where N where T, AbstractArray{T, N} where N where T) in module NLSolversBase at /home/febbo/.julia/v0.6/NLSolversBase/src/objective_types/oncedifferentiable.jl:114 overwritten in module NLsolve at /home/febbo/.julia/v0.6/NLsolve/src/objectives/autodiff.jl:2.

julia> Pkg.status("NLsolve")
 - NLsolve                       1.1.0

```

**Comment by pkofod** [comment]
Sorry, I'm way too busy these days. Yes I know what the problem is. Let me see if I can fix it and tag a new release.

**Comment by huckl3b3rry87** [comment]
I hear you. Times are busy... Thanks!

**Comment by pkofod** [comment]
this should fix it https://github.com/JuliaLang/METADATA.jl/pull/14694

**Comment by huckl3b3rry87** [comment]
@pkofod thank you for doing this.

I updated my packages, but the error persists. 
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating MAVs master...
INFO: Updating PrettyPlots master...
INFO: Updating NLOptControl master...
INFO: Updating AVExamples master...
INFO: Updating DegeneracyHunter master...
INFO: Updating MPCDocs master...
INFO: Updating VehicleModels master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using NLsolve
WARNING: Method definition (::Type{NLSolversBase.OnceDifferentiable{TF, TDF, TX} where TX where TDF where TF})(Any, AbstractArray{T, N} where N where T, AbstractArray{T, N} where N where T) in module NLSolversBase at /home/febbo/.julia/v0.6/NLSolversBase/src/objective_types/oncedifferentiable.jl:114 overwritten in module NLsolve at /home/febbo/.julia/v0.6/NLsolve/src/objectives/autodiff.jl:2.

julia> Pkg.status("NLsolve")
 - NLsolve                       1.1.0
```
Not a huge deal, I just wanted to follow up. Thanks and sorry for bugging you about this

**Comment by pkofod** [comment]
No problem. As you can see, that or is not merged yet :)

**Comment by huckl3b3rry87** [comment]
ahhhh. Opps. Thanks!

**Comment by pkofod** [comment]
try now

**Comment by pkofod** [comment]
@huckl3b3rry87 I hope your problem was fixed, but as I've seen that it helped others who had the problem, I'm closing. Please reopen as needed.
